spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 990706
    url: jdbc:mysql://localhost:3306/epidemic_ncov?serverTimezone=GMT%2B8

  thymeleaf:
    cache: false
    mode: HTML
    enabled: true
    encoding: utf-8
    check-template-location: true


mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.qzh.epidemic.entity

logging:
  config: classpath:log4j2.xml
